apiVersion: cloud.redhat.com/v1alpha1
kind: FrontendEnvironment
metadata:
  name: env-boot
spec: 
# Use hack/update-sso.sh to compute this for dev-sso auth domain 
  sso: "https://keycloak-dev-sso.apps.cluster-z9x66.z9x66.sandbox1324.opentlc.com/auth/" 
  ingressClass: openshift-default
  hostname: rhtap.apps.cluster-z9x66.z9x66.sandbox1324.opentlc.com
